((clojurescript-mode . ((cider-preferred-build-tool          . clojure-cli)
                        (cider-clojure-cli-global-options    . "-R:dev")
                        (cider-default-cljs-repl             . figwheel-main)
                        (cider-figwheel-main-default-options . "dev"))))
 ;; (clojure-mode . ()))
                  ;; (cider-preferred-build-tool          . clojure-cli)
                  ;; (cider-clojure-cli-global-options    . "-A:dev"))))
